CREATE DATABASE IF NOT EXISTS nutripaw;
USE nutripaw;

CREATE TABLE users (
user_id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(150) NOT NULL UNIQUE,
password_hash VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pets (
pet_id INT AUTO_INCREMENT PRIMARY KEY,
owner_id INT NOT NULL,
name VARCHAR(100) NOT NULL,
species VARCHAR(50) NOT NULL,
breed VARCHAR(100),
age INT,
gender VARCHAR(20),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_pet_owner
FOREIGN KEY (owner_id) REFERENCES users(user_id)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE food_entries (
food_entry_id INT AUTO_INCREMENT PRIMARY KEY,
pet_id INT NOT NULL,
food_type VARCHAR(100) NOT NULL,
amount DECIMAL(6,2) NOT NULL,
food_time TIME NOT NULL,
entry_date DATE NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_food_pet
FOREIGN KEY (pet_id) REFERENCES pets(pet_id)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE medications (
medication_id INT AUTO_INCREMENT PRIMARY KEY,
pet_id INT NOT NULL,
medication_name VARCHAR(100) NOT NULL,
medication_type VARCHAR(50) NOT NULL,
dosage VARCHAR(50) NOT NULL,
start_date DATE NOT NULL,
end_date DATE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CONSTRAINT fk_medication_pet
FOREIGN KEY (pet_id) REFERENCES pets(pet_id)
ON DELETE CASCADE
ON UPDATE CASCADE
);